### ISSUE TITLE
feat: Cut more releases

### ISSUE THREAD

**Issue by cafkafk** [numtide/flake-utils#107]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to only depend on semver tagged releases for my flake inputs.

**Describe the solution you'd like**

The last release was in May 21, 2022. Currently, this project seems to be at the end of it's development lifecycle. There are a few changes per month it seems. Perhaps a monthly semver tagged release (when there is changes) would be appropriate for flake-utils? 

**Describe alternatives you've considered**

Another option might be to cut a release on each commit, but having an amount of time where it's live but not releases would allow potential bugs to emerge.

**Additional context**

**Comment by Jayman2000** [comment]
I would also appreciate either a new release or some sort of clarification that GitHub Releases should not be used for this project (i.e., users should just use the main branch because this project is a continuous-deployment kind of project rather than a stable-release kind of project).

I noticed that [this issue was closed as completed](https://github.com/numtide/flake-utils/issues/107#event-10830225857), but there’s still no new `flake-utils` release. Could this issue be reopened?
